### ISSUE TITLE
Crash on entering world; Diamond Branch and damage types with looting

### ISSUE THREAD

**Issue by Not-February** [dainxt/AncientClasses#5]
``Ancient Classes 0.9.38``
``Forge 39.0.66``
``Minecraft 1.18.1``

Generate a fresh single player world, wait a few moments, and it crashes without me doing anything other than moving my camera around a bit. I didn't touch anything, I didn't interact with any entities, just went into the world and waited and it crashed a bit later.

It might be a mod conflict because I wasn't able to replicate this issue with just Ancient Classes in a standalone instance, but it is happening consistently in my larger modpack.

Crash log: https://gist.github.com/Febilian/294aec44da9adcce656acd7c9344c512

#4 seems similar and I am guessing that trying to fix that is what's causing this, so I've gone ahead and compared our mod lists to see what other mods we have in common just in case.
```
- Big Brain
- Shrines Structures
- JEI
- Caelus API
- Neat
- Terralith
- Meet Your Fight
- When Dungeons Arise
- Enchantment Descriptions
- TerraBlender
- Majrusz's Library
- Iceberg
- Curios
- Relics
- Collective
- AutoRegLib
- Quark
- Majrusz's Accessories
- Appleskin
- Curious Elytra
- Aquaculture
- Cosmetic Armor Reworked
- Player Revive
- GeckoLib
```

**Comment by dainxt** [comment]
Probably fixed in 0.9.39, let me know if possible to confirm it.

**Comment by Not-February** [comment]
Doesn't seem to be happening anymore, hopefully that's it!

**Comment by Coraline77447** [comment]
Even though you may have fixed this issue already but when I was looking through the logs to see what's going on cause I was trying to figure out why I wasn't able to obtain any blocks like dirt or wood (they would break and not drop anything at all like as if I was in creative mode when in fact I actually was in survival mode with cheats enabled. Btw at the time I didn't really think that this mod was causing the issue that I was experiencing and didn't do much testing with it along with Tinkers' Construct 3/Mantel).

Same thing had happened with my starter chest (bonus chest) that there was nothing in it and when I broke it it disappeared and the torches as well and I wanted my start chest and the torches, so I left that world and rejoined it to see if my starter chest and the torches would come back but they didn't..

Anyways, in one of the logs at the bottom was Ancient Classes with it's diamond branch (this was from one of the logs that Ancient Classes was logged in as an error during the firing event);

__[08:15:58] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.world.damagesource.DamageSource.m_7639_()" because the return value of "net.minecraftforge.event.entity.living.LootingLevelEvent.getDamageSource()" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.dainxt.ancientclasses.abilities.diamondbranch.DiamondBranchHandler@4f57cd2a onLooting(Lnet/minecraftforge/event/entity/living/LootingLevelEvent;)V__


After I read that part of the log I uninstalled Ancient Classes in fear of the game potentially crashing as a just in case procedure since I don't want to encounter any crashes at all costs.

Now I'm glad that I did since I highly suspected a crash coming if I were to have kept playing with Ancient Classes as of the version I currently have which isn't the latest version yet. 
(The original world that had Ancient Classes in it has been deleted and a remake of that world exists now but minus this mod until now since the issue with diamond branch should be fixed at last. Also both the original world and my remake world are for 1.18.1 btw)
